GITHUB_TOKEN = "ghp_...yourNewToken..."
GITHUB_OWNER = "your-username"
GITHUB_REPO  = "your-repo-name"
GITHUB_BRANCH = "main"
GITHUB_FILE_PATH = "payments.xlsx"
GITHUB_CUSTOMERS_PATH = "customers.xlsx"
GITHUB_REDEMPTIONS_PATH = "redemptions.xlsx"
